---
name: Haver-Core
version: 0.08
author:
  - Dylan William Hardison <dhardison@cpan.org>
abstract: Modules used by both Haver::Client and Haver::Server.
license: gpl
requires:
  Filter::Simple: 0
  POE: 0.29
  Spiffy: 0.21
  YAML: 0.35
  perl: 5.6.1
provides:
  Haver::Base:
    file: lib/Haver/Base.pm
    version: 0.08
  Haver::Config:
    file: lib/Haver/Config.pm
    version: 0.1
  Haver::Core:
    file: lib/Haver/Core.pm
    version: 0.08
  Haver::Logger:
    file: lib/Haver/Logger.pm
    version: 0.02
  Haver::Protocol:
    file: lib/Haver/Protocol.pm
    version: 0.03
  Haver::Protocol::Filter:
    file: lib/Haver/Protocol/Filter.pm
    version: 0.02
  Haver::Session:
    file: lib/Haver/Session.pm
    version: 0.08
  Haver::Util:
    file: lib/Haver/Util.pm
    version: 0.02
  Haver::Wheel:
    file: lib/Haver/Wheel.pm
    version: 0.08
  Haver::Wheel::Loader:
    file: lib/Haver/Wheel/Loader.pm
    version: 0.04
generated_by: Module::Build version 0.26
